### ISSUE TITLE
Limitations on ashuffle

### ISSUE THREAD

**Issue by JST1963** [joshkunz/ashuffle#14]
Hi, I'm using the wonderful moOde to stream music from my NAS using a RPi3 and RPi3B+.
My collection of albums exceeds the number of 4200 with over 74000 songs.
When I now want to "ashuffle" through this complete library, ashuffle won't work anymore. This already happens when I have more than 42000 songs in my library. As soon as I start the random selection icon, I can see in SSH that ashuffle uses up to 99.9% of the CPU but after a minute the process ashuffle disappears from the list (Did it stop? Did it crash? I don't know).
So now I'm wondering: is there a limitation on the number of songs (42000 in my case, someone said 33000 on a PiZero) or is there a time limit, meaning if the system still hasn't selected a song after one minute, then the whole process stops.
Thx in advance for your fast response.

Johan

**Comment by joshkunz** [comment]
> So now I'm wondering: is there a limitation on the number of songs (42000 in my case, someone said 33000 on a PiZero) or is there a time limit, meaning if the system still hasn't selected a song after one minute, then the whole process stops.

As currently written, `ashuffle` store a list of all (just the path to each file relative to the MPD root) songs in memory. On severely memory constrained devices like the RPi, with large libraries, it’s possible that just storing this list consumes more memory than is available on the device. I think there are two separate issues at play here:

1. Poor error handling in low-memory conditions.
2. Optionally storing library listing on disk.

Starting with (1): `ashuffle`’s current handling of allocation errors is poor, and I should make it crash in a more expected way. It’s likely that what is happening is either that ashuffle is getting OOM’d by the kernel when it starts consuming too much memory, or some allocations are failing and ashuffle is crashing. Either way, you should be able to look at the MoOde logs to see why ashuffle is failing to run. I’m not affilicated with moOde, and I’ve never used it, so I don’t really know how to do this, sorry.

For (2): Storing ashuffle data on disk is a reasonable request, and since ashuffle is bundled in systems like moOde, it seems like `ashuffle` is often run on large libraries in memory-constrained environments. I’ve opened issue #16 to track this.

I’ll leave this issue open until the fixes to (1) are committed.

**Comment by joshkunz** [comment]
The the advantage of hindsight, the problem described in the original issue actually sounds a lot like #31. This library is pretty large (72k tracks), but we are now performance-testing startup on a 20k-track library at under 1s. 72k is more than triple that size, but the scaling shouldn't be *that* bad. So this should be resolved. The OOM idea I posed is probably wrong, see [this comment](https://github.com/joshkunz/ashuffle/issues/16#issuecomment-662236796) for details. Since I think this was fixed in #31, I'm closing this as obsolete. Please re-open if the latest version of ashuffle still has this problem.
