### ISSUE TITLE
Pattern request

### ISSUE THREAD

**Issue by moodeaudio** [joshkunz/ashuffle#17]
Hi,

I was looking through some of the user requests from the moOde community about Auto Shuffle and a a fairly common one is to have the ability to only include certain genres for example only Genre = Classical.

Currently the only way to achieve this that I'm aware of is by using --exclude to exclude all but the desired genre.

If there were a --include option it would make this very easy.

-Tim

**Comment by joshkunz** [comment]
Include was omitted on purpose since it makes the matching language more complicated, and all use-cases I could think of are handled by the existing `-f`/`--file` option. For example, if you wanted to shuffle only classical songs you could run a command like: `mpc search genre Classical | ashuffle --file -` to include only the songs found via the search done by `mpc`.

**Comment by moodeaudio** [comment]
The file option works perfectly :-)
