### ISSUE TITLE
FR: Add option to automatically curtail MPD playlist to a certain maximum length

### ISSUE THREAD

**Issue by purrloftruth** [joshkunz/ashuffle#19]
Hi there,

I use ashuffle in an automated, unsupervised environment. What typically happens is that I will forget about it for several months, and MPD will eventually crash when its playlist grows large enough, leading the automation to stop working and require MPD and ashuffle to be manually restarted. I cannot seem to find any information on the internet about a built-in configuration option for MPD that would allow it to remove old tracks from the playlist automatically. It would be great if ashuffle could contain this functionality, though I understand if it might be a bit too niche for what you're doing. Either way, thank you so much for all your hard work! It's been completely indispensable to me.

**Comment by purrloftruth** [comment]
Nevermind me. I finally figured out "consume". Which I probably had figured out years ago, which is why I spent so much time looking for the information on it only to come up with nothing because I wasn't looking for the right term.

**Comment by martinetd** [comment]
I'm actually interested in this even if the consume mpd option exists.
The reason is that depending on my mood I might want to come back to the track that's just done playing.

Having a constant backlog of e.g ~10 songs would be awesome, a bit like --queue_buffer but the other way around.

Right now since I don't want to use consume for the reason mentioned above I would have to remember to 'mpc crop' once in a blue moon; I could probably just put that in a crontab but it's just not as elegant...


Happy to do this myself and send a PR if that'd have a chance of getting accepted - something trivial that just call `mpd_status_get_song_pos()` and `mpd_run_delete_range(.., 1, pos - <whatever is configured>)` in `try_enqueue(), give or take off-by-one errors and overflow checks; but I'd understand if you don't want to add bloat, and it's less work for me to keep my version with hardcoded values in this case :p

Thanks,

**Comment by joshkunz** [comment]
“max backlog” seems like it could just as easily be implemented in a separate MPD client. I don’t think it’s worth the extra code/interface complexity. 

That said, it might be interesting to try and extract the queue update logic from ashuffle and make it more easily port-able to other use cases.

I’ll leave this bug closed :smile:
