### ISSUE TITLE
queue_buffer: does not work in background

### ISSUE THREAD

**Issue by thenktor** [joshkunz/ashuffle#30]
Hi,
for some reason the queue_buffer argument does not work, when I launch ashuffle in background:
`ashuffle --queue_buffer 2 &`

Same problem when I pipe output to /dev/null:
`ashuffle --queue_buffer 2 > /dev/null`

In both cases songs are added to the queue, but only one song when the queue finishes. If I just start `ashuffle --queue_buffer 2` in foreground there are always 2 songs at the end of the queue as expected.

**Comment by joshkunz** [comment]
Thanks for filing an issue! Unfortunately, I'm not able to reproduce this issue locally. Could you provide more information about your setup? MPD version, libmpdclient version, ashuffle version? Maybe even an MPD config. Since this is related to I/O redirection and backgrounding, your shell version and OS version would also be good to know. I'm not sure what mechanism could cause this behavior.

> In both cases songs are added to the queue, but only one song when the queue finishes.

I'm not sure what you mean here. The queue actually completes? With `--queue_buffer` the queue should never "complete", since there should always be another song to play. That seems odd...

**Comment by thenktor** [comment]
Hi,

I'm starting ashuffle in a Shell script in a docker container. I'll try again and give feedback about my used versions.

**Comment by thenktor** [comment]
Hi,
issue can be closed. I cannot even reproduce it myself.

Sorry for inconvenience!
