### ISSUE TITLE
High CPU usage on startup when using --file option

### ISSUE THREAD

**Issue by thenktor** [joshkunz/ashuffle#31]
Hi,

I'm using a file with songs, that ashuffle should use (generated with mpc). The file has ~17.000 songs. I'm starting ashuffle like this: `ashuffle --queue_buffer 2 --file /tmp/ashuffle-songlist.txt`
After ashuffle has started the CPU usage of mpd goes up to 100 % (one core fully loaded) for several minutes (measured 8 minutes on last try). Time increases with longer song lists. 
CPU is a i5-4570 @ 3.20GHz. 

During this time no songs are added to the queue.

There probably is some communication between ashuffle and mpd about the song list. Why and can it be deactivated?

**Comment by thenktor** [comment]
The `--nocheck` option fixes this. But actually the description implies that this option is only useful, when also `--exclude` is given:
When reading URIs from a file, don't check to ensure that the URIs match the given exclude rules. This option is most helpful when shuffling songs with -f, that aren't in the MPD library.

**Comment by joshkunz** [comment]
When ashuffle is started with the `-f` option, it still tries to apply the exclusion rules (set with `--exclude`). This works by querying MPD for each song in the song list to verify that it is both A) a valid song in MPD, and B) it does not match any of the exclusion rules. I think this is what you're running into. With a large song-list, ashuffle will synchronously execute these queries, and it is probably swamping MPD.

`--nocheck` fixes the issue because it disables this checking. I didn't mention it in the docs because it didn't occur to me that it could affect performance 😀. There is a simple fix to make this "edge" a little less sharp: We can skip this processing if no exclusion rules are set. Basically implicitly enable "no check". Unfortunately this is a bit of an API break, since right now `ashuffle` will detect if you supply invalid URIs to `-f`, and implicitly enabling nocheck would disable that behavior. I'm going to be cutting a v2 release soon, so I'll consider including this break then. Until then, I advise using `--nocheck`.

Longer term, we should still handle large libraries even if they set exclusion rules. I chatted about this with @huctica the other day, and he had the idea of lazily processing exclusion rules, so we can amortize their evaluation (i.e. we can process a small number of songs quickly, queue them, then check the rules against the remaining songs in the background). This seems like a good approach to me.

I'm going to leave this bug open to track:
* Implying `--nocheck` when there are no exclusion rules in v2.
* Benchmarking (and tracking) startup performance with large libraries.
*  Lazily evaluating rules for URIs given with `-f`.

**Comment by joshkunz** [comment]
Both the startup time issue, and the benchmarking should be resolved with PR #47. I will follow-up with tracking the lazy rule evaluation (which looks to be somewhat complex in its own right) in issue #48.
