### ISSUE TITLE
Connect with password?

### ISSUE THREAD

**Issue by wonaldson** [Joshkunz/ashuffle#5]
As far as I can tell this project doesn't offer any way to connect to a MPD instance that is password-protected. Is there any possibility that this can be implemented? I would love to use this software for a project I'm working on.

Thanks very much!

**Comment by Joshkunz** [comment]
I'll take a look at what would be involved for this. It shouldn't be too bad.

**Comment by Joshkunz** [comment]
@wonaldson 

Alright, I think I've got a solution for this, can you try applying this patch <https://github.com/Joshkunz/ashuffle/compare/master...mpd-password-support.patch>? Let me know if it works and I'll merge it into master.

You can apply it with:
```
curl https://github.com/Joshkunz/ashuffle/compare/master...mpd-password-support.patch | git apply -
```

**Comment by wonaldson** [comment]
Sorry for the delay in responding. This works great! :) Is there any way that that password can be saved, or entered on the command line? Ideally I would be starting this process after MPD on boot.

Thanks again for your help with this! I really appreciate it. (I've done a brief write-up on what I'm doing with it [over here](http://wildonaldson.me/portfolio/playful-stream/), if you're interested.)

**Comment by Joshkunz** [comment]
@wonaldson I added support for supplying the password via the `MPD_HOST` environment variable which seems to be the standard way to do it (it's the way mpc and ncmpc do it). I wrote up how to use it in [the readme](https://github.com/Joshkunz/ashuffle#running-in-a-non-standard-configuration). 

Also, yeah, I've merged these changes into `master` so this issue is officially closed. Thanks for crediting ashuffle in your writeup, it looks like a cool project. I'm glad someone else thought it was useful.
