### ISSUE TITLE
Can't build on Raspberry Pi 3

### ISSUE THREAD

**Issue by ge-ps** [joshkunz/ashuffle#65]
I get meson error while trying to build ashuffle 3.5.0 on RPI3 following step-by-step instructions.

Here is the meson log:

`Build started at 2020-06-08T18:40:01.583197
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.49.2
Source dir: /home/pi/ashuffle
Build dir: /home/pi/ashuffle/build
Build type: native build
Project name: ashuffle
Project version: undefined
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /home/pi/ashuffle/build/meson-private/sanitycheckc.c -o /home/pi/ashuffle/build/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/pi/ashuffle/build/meson-private/sanitycheckc.exe
Native C compiler: cc (gcc 8.3.0 "cc (Raspbian 8.3.0-6+rpi1) 8.3.0")
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ /home/pi/ashuffle/build/meson-private/sanitycheckcpp.cc -o /home/pi/ashuffle/build/meson-private/sanitycheckcpp.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/pi/ashuffle/build/meson-private/sanitycheckcpp.exe
Native C++ compiler: c++ (gcc 8.3.0 "c++ (Raspbian 8.3.0-6+rpi1) 8.3.0")
Build machine cpu family: arm
Build machine cpu: armv7l

meson.build:25:2: ERROR:  Module "cmake" does not exist`

**Comment by gearhead** [comment]
on Arch Linux, the instructions work for me on RPI B3 and B1 (armv6/7).

**Comment by joshkunz** [comment]
@ge-ps Thanks for including all this info in your report! As per https://github.com/joshkunz/ashuffle#dependencies, a Meson version of at least 0.54.0 is required to build ashuffle. Consider upgrading Meson from your package manager, or [installing a newer version with pip](https://mesonbuild.com/Getting-meson.html#installing-meson-with-pip).

Ideally, you could just use the binary distributions included with the release, instead of having to compile from source. Unfortunately, I overlooked that Raspberry Pi OS is 32-bit only, even though RPi 3+ are actually running 64-bit capable chips 😅. I've opened #66 to fix this oversight.
