### ISSUE TITLE
Playlist is restarted when a file is not found

### ISSUE THREAD

**Issue by vesubian** [joshkunz/ashuffle#94]
I am experimenting with a web radio so I have a continuous broadcast of a large library playing at random with ashuffle.

Sometimes a file is not found (did not find the reason yet, maybe just need an `mpc update` to run).

In such cases, the playlist is started over and replayed. If I delete the unfound file and play the last track on the playlist, then ashuffle takes over again.

I would expect/like ashuffle to skip through the unfound file and pick another one instead, and in any case to keep on going. 

I use ashuffle with a queue buffer of 1 to allow mpd crossfade.

**Comment by joshkunz** [comment]
Very interesting... that does sound like a bug, currently `ashuffle` generally (purposefully) crashes when it encounters an MPD error, so that could be causing this odd behavior. I'll see if I can get a repro based on the description.

Do you know what versions of ashuffle/MPD you're running as well? If you could add [`log_level "verbose"`](https://www.musicpd.org/doc/html/user.html#troubleshooting) to your `mpd.conf`, reproduce the issue, and then attach the MPD log here, that would also be helpful. Including any output from ashuffle would be helpful as well.

**Comment by martinetd** [comment]
That's not an mpd error, mpd will let you queue non-existing files if they are in its db, then it will skip it when trying to play it -- skipping it means it'll skip straight to the start because he must have repeat on.

Disabling repeat might cause mpd to stop for a minute but will probably work if ashuffle gets it to resume playback (not sure it does), the easiest solution would be to just have a queue buffer long enough to ensure there aren't <queue buffer length> missing files in a row... I don't believe it's ashuffle's job to check the files exist

**Comment by vesubian** [comment]
You are right, I had `repeat `on, which I disabled when I realized. I will also set the queue to 2 tracks then.

Also I start ashuffle with `play-on-startup` so I think you are right it should keep on playing this way.

I tried reproducing the issue by moving away the next file in queue. Now the track is simply replaced by ashuffle which is great.

Thank you for your help! It's a great tool I love it, so much more elegant than to queue the whole library and playing it randomly.

**Comment by joshkunz** [comment]
Thanks for the help @martinetd!

> Might cause mpd to stop for a minute but will probably work if ashuffle gets it to resume playback (not sure it does)...

ashuffle considers [any song position past the end of the queue](https://github.com/joshkunz/ashuffle/blob/ccb5e9ada75d97e03407c393d485d59d70da46c8/src/ashuffle.cc#L54) to mean it should add a song, reguardless of play/pause/stop state. So it should enqueue in this case, and it looks like @vesubian confirmed that.

> I don't believe it's ashuffle's job to check the files exist.

I think I agree here. The UX of this kinda sucks though. It seems like maybe we should warn the user that this might happen. It's tricky though because I could imagine this being noisy for users who expect ashuffle to be effectively deactivated when repeat mode is on. Maybe just a section in the `readme` about using ashuffle with `repeat` would be sufficient here?

>  It's a great tool I love it...

Thanks @vesubian, glad you like it!

**Comment by martinetd** [comment]
> I think I agree here. The UX of this kinda sucks though. It seems like maybe we should warn the user that this might happen. It's tricky though because I could imagine this being noisy for users who expect ashuffle to be effectively deactivated when repeat mode is on. Maybe just a section in the readme about using ashuffle with repeat would be sufficient here?

Automatically deactivating ashuffle if repeat is on might make sense -- I sometimes actually want repeat and need to kill ashuffle for that day/hours/period to get it to work, that's a bit manual :)
OTOH it would probably break some working setups if the users never noticed they had left repeat on so we need to be careful... Automatically turning repeat off when ashuffle starts seems a bit forceful though, not sure what to advise.
