### ISSUE TITLE
Add something like a --daemonize flag

### ISSUE THREAD

**Issue by kartikynwa** [joshkunz/ashuffle#97]
Hello.

Thanks for writing ashuffle. I use it daily and love it.

I usually use ashuffle from the command line and make sure it runs in the background I do something like:

```
mpc listall some_folder | ashuffle -f - & disown
```

For this use case a flag that makes ashuffle fork to the background would be useful.

Please feel free to close the issue if the feature isn't deemed desirable.

Thanks.

**Comment by joshkunz** [comment]
> Thanks for writing ashuffle. I use it daily and love it.

Glad to hear you like it!

> For this use case a flag that makes ashuffle fork to the background would be useful.

What problems would this solve for you compared to running `ashuffle` directly from the command line?

My general opinion on this is that backgrounding is better handled by the shell (as you do here), or a daemon manager like systemd/daemontools. With bespoke daemonization, it's not clear how to stop the process, and doing straightforward integration with something like systemd can be tricky since invocations that work on the command line won't work in systemd.It also also adds yet another command users have to learn. Plus, `ashuffle` is already pretty POSIX specific, but daemonization may require more arch-specific code to ensure that things like PID files are stored in the correct directory.

Would making the steps required for daemonization more obvious be helpful? For example, we could explain how to run ashuffle in the background in the main readme. I'd potentially even be open to automating systemd setup or something.

**Comment by kartikynwa** [comment]
> What problems would this solve for you compared to running ashuffle directly from the command line?

Being able to close the terminal emulator window after starting ashuffle.

> Would making the steps required for daemonization more obvious be helpful?

I think this would be more than enough. Even if you could elucidate on that here instead of adding it to the README that would be great.

**Comment by joshkunz** [comment]
> Being able to close the terminal emulator window after starting ashuffle.

What is wrong with:

```
ashuffle ... & disown
```

That's my question. That pattern should let you close the shell, and ashuffle will remain running in the background. Every shell has some kind of background/disown functionality that should work for this case.

> I think this would be more than enough.

What kind of daemonization are you looking for? Something like setting it up for systemd? Just run in the background? Another user has [actually contributed](https://github.com/joshkunz/ashuffle/tree/master/contrib/systemd) systemd instructions. I can link those from the readme to make them more discoverable. I'd be OK adding instructions for running ashuffle in the background with a shell as well.

**Comment by kartikynwa** [comment]
I think you are correct. This feature isn't needed. I just wasn't sure if `& disown` is the proper way to handle this since I hadn't used it before but from what you're saying there's nothing wrong with it.

Thanks for the link to the systemd related stuff too. Might come in handy later.
